name: Sync Release to S3

on:
  release:
    types: [published]

jobs:
  sync-to-s3:
    name: Upload Release Assets to S3
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Get release info
        id: release
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Download release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Download all assets from the release
          gh release download ${{ steps.release.outputs.tag }} \
            --repo ${{ github.repository }} \
            --pattern "*.dmg" \
            --pattern "*.xml"
          
          # List downloaded files
          echo "Downloaded files:"
          ls -lh
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Upload versioned DMG to S3
        run: |
          aws s3 cp "Picflow-${{ steps.release.outputs.version }}.dmg" \
            "s3://picflow-webapp-prod/macos/Picflow-${{ steps.release.outputs.version }}.dmg" \
            --cache-control "public, max-age=31536000, immutable" \
            --content-type "application/x-apple-diskimage"
          
          echo "✅ Uploaded versioned DMG: Picflow-${{ steps.release.outputs.version }}.dmg"
      
      - name: Upload latest DMG to S3
        run: |
          aws s3 cp "Picflow.dmg" \
            "s3://picflow-webapp-prod/macos/Picflow.dmg" \
            --cache-control "public, max-age=300" \
            --content-type "application/x-apple-diskimage"
          
          echo "✅ Uploaded latest DMG: Picflow.dmg (overwrites previous)"
      
      - name: Upload appcast.xml to S3
        run: |
          aws s3 cp "appcast.xml" \
            "s3://picflow-webapp-prod/macos/appcast.xml" \
            --cache-control "public, max-age=3600, must-revalidate" \
            --content-type "application/rss+xml"
          
          echo "✅ Uploaded appcast.xml (overwrites previous)"
      
      - name: Summary
        run: |
          echo "## 🎉 Release Synced to S3" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Files uploaded to S3:**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ \`Picflow-${{ steps.release.outputs.version }}.dmg\` (versioned, immutable)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ \`Picflow.dmg\` (latest, overwrites)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ \`appcast.xml\` (update feed)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**S3 Location:** \`s3://picflow-webapp-prod/macos/\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Public URLs:**" >> $GITHUB_STEP_SUMMARY
          echo "- Versioned: \`https://picflow.com/download/macos/Picflow-${{ steps.release.outputs.version }}.dmg\`" >> $GITHUB_STEP_SUMMARY
          echo "- Latest: \`https://picflow.com/download/macos/Picflow.dmg\`" >> $GITHUB_STEP_SUMMARY
          echo "- Update feed: \`https://picflow.com/download/macos/appcast.xml\`" >> $GITHUB_STEP_SUMMARY

